### ISSUE TITLE
New releases are needed (to remove the username of the backdoor author)

### ISSUE THREAD

**Issue by Neustradamus** [tukaani-project/xz#119]
Dear @Larhzu,

Several people would like that you do new releases (to remove the username of the backdoor author) and good asset files:
- https://github.com/tukaani-project/xz/releases

And maybe good to remove the 5.6.x tags too?
- https://github.com/tukaani-project/xz/tags

Note: Same in primary git source place.

Thanks in advance.

**Comment by thesamesam** [comment]
This is already being covered in https://github.com/tukaani-project/xz/issues/103 (and https://github.com/tukaani-project/xz/issues/107). Please be patient.

**Comment by Neustradamus** [comment]
@thesamesam: I can not participate on your tickets, there is a problem.

**Comment by thesamesam** [comment]
How did you write this comment and the other one 
?

**Comment by Neustradamus** [comment]
@thesamesam: It is easy, please unblock me.

**Comment by thesamesam** [comment]
I have already, but I don't get how you're able to comment if you're saying you can't participate.

I also suggest reflecting on why someone might block you to begin with.
