### ISSUE TITLE
Release new version for merged PR #136?

### ISSUE THREAD

**Issue by awesomebytes** [tukaani-project/xz#139]
Hello, thanks for supporting this project and for your awesome attitude towards users.

In order to receive the patch from: https://github.com/tukaani-project/xz/pull/136

Would it be possible to release a new version? I would guess 5.6.3. I do not know what's your release cadence or rules, I did try to check on your website and the repo README, I apologize if I overlooked it.

Thank you!

**Comment by Larhzu** [comment]
I picked something into v5.6_dev but I don't know yet if it is what I want to put into v5.6. The CMake changes in master are big and some are related to liblzma code changes. So I don't really feel like backporting them but, on the other hand, only the full CMake changes in master make the CMake support (hopefully) good. Perhaps those can wait for 5.7.1alpha.

There are enough fixes in v5.6_dev that make a new release worth doing. I don't promise any schedule. Package managers tend to have an easy way to include patch files in the build. Extracting the patch from the Git repo to build 5.6.2 isn't that much work in such a situation. But I know it's annoying if building manually and in similar cases.
