### ISSUE TITLE
Important piece of information omitted in the description of the `-d` option, to decompress

### ISSUE THREAD

**Issue by Ricky-Tigg** [tukaani-project/xz#150]
Hello. Having a __.bin.xz_ file to decompress, I started by looking for the instruction in the `man`-page. There, for the relevant part, we have.
```
-d, --decompress, --uncompress
 Decompress.
```
What we will learn however by running a command with this option alone, is that it not only **decompresses** the original compressed file, but also **deletes it**, leaving us with only the contents of the decompressed file.

PS.: I don't know now how to proceed in order to introduce the file thus deleted into my system. What a hassle!

**Comment by thesamesam** [comment]
Your message isn't easy to parse, but the gist appears to be that you think we shouldn't duplicate, but move the sentence. Sure. I think that moves into editorial nits which @Larhzu and I can discuss.

> Finally, regarding this option, if you would allow me a suggestion, it would not be too wise to express it unambiguously, 

I think you mean "unwise".

> So I'm not yet inclined to try to compress again the contents of the decompressed file.

Sure, that's your decision. But your original post said you had no idea how to try get it back, I offered the only option outside of backups.

**Comment by thesamesam** [comment]
I'm not going to try split hairs about this, but I want to say that "not be too wise" means "it would not be a good idea", and you meant "it would be a good idea to phrase it like this", not the opposite.

Anyway, we'll discuss tweaking the man page. Thanks.

**Comment by eli-schwartz** [comment]
> * As for the language barrier, which is the case, as you must easily understand, I cannot have any power over others in this matter

In my experience, AI rewording tools perform significantly worse than the simpler, more robust and more reliable translation tools that have existed for far longer.

> If I had known that through a seemingly innocent report, some internal problem would be revealed, I would have been careful not to post here. It gives a reliable indication of the health of the project. Should we therefore be surprised that there was a notorious back-door to be counted to its credit?

What internal problem? What health issue? How does this connect to backdoors?

Deleting the original input is behavior that has traditionally been performed by compressor/decompressor programs. GNU gzip does it, `ncompress` does it, bzip2 does it... and in fact, gzip's manpage is rather similar to xz in this regard as well (as is bzip2):

```
The  gzip  command reduces the size of the named files using Lempel-Ziv coding (LZ77).  Whenever possible, each file is replaced by one with the extension .gz,

[...]

       -d --decompress --uncompress
              Decompress.

       -k --keep
              Keep (don’t delete) input files during compression or decompression.
```


It's definitely not an "internal problem" for a program to behave in the manner in which it is documented to behave.
