### ISSUE TITLE
brew install xz的时候提示  deny_network_access。

### ISSUE THREAD

**Issue by WuJieFly** [tukaani-project/xz#154]
环境信息：
mac m1 
os big sur 11.3
743ec0a46654afe22d5ecbe5c3c712c251857d3548c15adcb69345--xz.rb
Error: xz: undefined method `deny_network_access!' for Formulary::FormulaNamespace7ca23d67df04b730c79d07186c0edad6::Xz:Class

如何解决这个  错误？

**Comment by tarunKakani** [comment]
Hi , I also had the same issue but mine worked after I ran:

brew cleanup
brew install xz --force 

if this doesn't work for you or you don't want to install with --force you could : 
- reinstall homebrew 
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh)"
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

- Or you could try installing a specific version of xz or a older version of it that works

I hope it helps.

**Comment by thesamesam** [comment]
This sounds like a Homebrew packaging issue to me, I'm afraid.

**Comment by thesamesam** [comment]
cc @carlocab -- any idea?

**Comment by carlocab** [comment]
It seems like the version of `brew` that you're using is too old for the `xz` formula (package definition) that you want to install.

Try doing `brew update`. If that doesn't help, paste the output of `brew config` and `brew doctor` here.
