### ISSUE TITLE
[Bug]: Unable to install via conan, tukanni.org is down

### ISSUE THREAD

**Issue by snweiss** [tukaani-project/xz#78]
### Describe the bug

Trying to install xz_utils via conan - 
```
xz_utils/5.4.2: Sources downloaded from 'conancenter'
xz_utils/5.4.2: Calling source() in C:\Users\ContainerAdministrator\.conan2\p\xz_ut55e9abba365d4\s\src
xz_utils/5.4.2: ERROR: Error downloading file https://tukaani.org/xz/xz-5.4.2.tar.gz: 'HTTPSConnectionPool(host='tukaani.org', port=443): Read timed out. (read timeout=60)'
```

Seems like https://tukaani.org is down for the past week

### Version

5.4.2

### Operating System

Windows 11

**Comment by Larhzu** [comment]
Seems to work fine at the moment. The hosting provider had reported that a denial of service attack happened 2-3 days ago.

The 5.4.2 release is available on GitHub and also on [Sourceforge](https://sourceforge.net/projects/lzmautils/files/). Future release will use github.com as the primary download URL for unrelated reasons.
